### ISSUE TITLE
mark 2.1.2 as latest release?

### ISSUE THREAD

**Issue by chenrui333** [neovim/unibilium#28]
👋 looks like 2.1.2 did not get marked as latest release as previous releases, raise this issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/189370

**Comment by justinmk** [comment]
https://github.com/neovim/unibilium/releases/tag/v2.1.2

**Comment by dundargoc** [comment]
We might wanna go with automated releases for our less important repos. @clason has used release-please IIRC, any thoughts?

**Comment by clason** [comment]
I think this is the only non-Neovim repo that is used outside Neovim itself (and gets so few updates), so that sounds like overkill. We just have to remember that releasing is not the same as tagging, or live with the friendly homebrew reminder (which does not accept pure tags) from time to time.
